# Deploy-RustDesk-Enhanced.ps1
# 增强版RustDesk部署脚本 - 支持安装后自动获取ID

param(
    [string]$InstallerPath = "rustdesk.exe",
    [string]$InstallPath = "C:\Program Files\RustDesk",
    [string]$Password = "",
    [string]$CustomID = "",
    [bool]$NoDesktopLink = $true,
    [string]$LogFile = "C:\Deploy\rustdesk_deployment.log"
)

Write-Host "=== RustDesk 增强部署脚本 ===" -ForegroundColor Cyan
Write-Host ""

# 确保日志目录存在
$logDir = Split-Path $LogFile -Parent
if (-not (Test-Path $logDir)) {
    New-Item -ItemType Directory -Path $logDir -Force | Out-Null
}

# 1. 静默安装（现在会自动生成配置）
Write-Host "[1/5] 静默安装 RustDesk..." -ForegroundColor Yellow
$installArgs = @("--silent-install", "--path=`"$InstallPath`"")
if ($NoDesktopLink) {
    $installArgs += "--nolink"
}

Write-Host "安装参数: $($installArgs -join ' ')" -ForegroundColor Gray

# 捕获安装输出（包含自动生成的ID）
$output = & $InstallerPath $installArgs 2>&1 | Out-String
Write-Host $output

# 从安装输出中提取ID
$installedID = $null
if ($output -match 'RustDesk ID:\s*(\d{9,10})') {
    $installedID = $matches[1]
    Write-Host "✅ 安装成功！自动生成的ID: $installedID" -ForegroundColor Green
} else {
    Write-Host "⚠️ 未能从安装输出获取ID，尝试从配置文件读取..." -ForegroundColor Yellow
    Start-Sleep -Seconds 2
    
    # 备用方案：从配置文件读取
    $configPath = "$env:APPDATA\RustDesk\config\RustDesk.toml"
    if (Test-Path $configPath) {
        $config = Get-Content $configPath -Raw
        if ($config -match 'id\s*=\s*[''"]?(\d{9,10})[''"]?') {
            $installedID = $matches[1]
            Write-Host "✅ 从配置文件获取ID: $installedID" -ForegroundColor Green
        }
    }
}

if (-not $installedID) {
    Write-Host "❌ 无法获取ID！" -ForegroundColor Red
    exit 1
}

Write-Host ""

# 2. 设置密码（如果指定）
if ($Password) {
    Write-Host "[2/5] 设置密码..." -ForegroundColor Yellow
    Start-Process "$InstallPath\rustdesk.exe" `
        -ArgumentList "--password", $Password `
        -Verb RunAs -Wait
    Write-Host "✅ 密码已设置" -ForegroundColor Green
} else {
    Write-Host "[2/5] 跳过密码设置" -ForegroundColor Gray
}

Write-Host ""

# 3. 设置自定义ID（如果指定）
$finalID = $installedID
if ($CustomID) {
    Write-Host "[3/5] 设置自定义ID: $CustomID..." -ForegroundColor Yellow
    Start-Process "$InstallPath\rustdesk.exe" `
        -ArgumentList "--set-id", $CustomID `
        -Verb RunAs -Wait
    $finalID = $CustomID
    Write-Host "✅ 自定义ID已设置" -ForegroundColor Green
} else {
    Write-Host "[3/5] 使用自动生成的ID: $installedID" -ForegroundColor Gray
}

Write-Host ""

# 4. 验证配置
Write-Host "[4/5] 验证配置..." -ForegroundColor Yellow
$configPath = "$env:APPDATA\RustDesk\config\RustDesk.toml"
if (Test-Path $configPath) {
    Write-Host "✅ 配置文件存在: $configPath" -ForegroundColor Green
    
    # 显示配置摘要
    $config = Get-Content $configPath -Raw
    if ($config -match 'id\s*=\s*[''"]?([^''"]+)[''"]?') {
        Write-Host "   ID: $($matches[1])" -ForegroundColor Cyan
    }
    if ($config -match 'salt\s*=\s*[''"]?([^''"]+)[''"]?') {
        Write-Host "   Salt: $($matches[1])" -ForegroundColor Cyan
    }
    if ($config -match 'key_confirmed\s*=\s*(\w+)') {
        Write-Host "   Key Confirmed: $($matches[1])" -ForegroundColor Cyan
    }
} else {
    Write-Host "⚠️ 配置文件不存在" -ForegroundColor Yellow
}

Write-Host ""

# 5. 启动服务
Write-Host "[5/5] 启动 RustDesk 服务..." -ForegroundColor Yellow
Start-Process "$InstallPath\rustdesk.exe" `
    -ArgumentList "--service" `
    -Verb RunAs

Start-Sleep -Seconds 2
$service = Get-Process -Name "rustdesk" -ErrorAction SilentlyContinue
if ($service) {
    Write-Host "✅ 服务已启动（PID: $($service.Id)）" -ForegroundColor Green
} else {
    Write-Host "⚠️ 服务未检测到，可能需要手动启动" -ForegroundColor Yellow
}

Write-Host ""

# 生成部署报告
$report = @"
========================================
    RustDesk 部署报告
========================================

部署时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
计算机名: $env:COMPUTERNAME
用户名: $env:USERNAME
域名: $env:USERDOMAIN

安装信息:
  安装路径: $InstallPath
  配置文件: $configPath
  桌面快捷方式: $(if ($NoDesktopLink) {'否'} else {'是'})

设备信息:
  自动生成ID: $installedID
  最终ID: $finalID
  密码已设置: $(if ($Password) {'是'} else {'否'})
  自定义ID: $(if ($CustomID) {$CustomID} else {'无'})

服务状态:
  进程运行: $(if ($service) {'是 (PID: ' + $service.Id + ')'} else {'否'})

快速连接:
  rustdesk.exe --connect $finalID --password <密码>

========================================
"@

Write-Host $report -ForegroundColor Cyan

# 保存到日志文件
Add-Content -Path $LogFile -Value "`n$report`n"
Write-Host "✅ 部署报告已保存到: $LogFile" -ForegroundColor Green

# 导出ID到CSV（便于批量收集）
$csvPath = Join-Path $logDir "rustdesk_ids.csv"
$csvExists = Test-Path $csvPath
$csvData = [PSCustomObject]@{
    Timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    ComputerName = $env:COMPUTERNAME
    UserName = $env:USERNAME
    Domain = $env:USERDOMAIN
    RustDeskID = $finalID
    AutoGeneratedID = $installedID
    CustomID = $(if ($CustomID) {$CustomID} else {'N/A'})
    InstallPath = $InstallPath
    PasswordSet = $(if ($Password) {'Yes'} else {'No'})
}

if ($csvExists) {
    $csvData | Export-Csv -Path $csvPath -NoTypeInformation -Append
} else {
    $csvData | Export-Csv -Path $csvPath -NoTypeInformation
}

Write-Host "✅ ID已添加到CSV: $csvPath" -ForegroundColor Green

Write-Host ""
Write-Host "=== 部署完成 ===" -ForegroundColor Green
Write-Host "RustDesk ID: $finalID" -ForegroundColor Yellow -BackgroundColor DarkBlue
